# Generated by Django 5.1.6 on 2025-02-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
