# Generated by Django 5.1.6 on 2025-02-12 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 2, 12, 7, 2, 35, 52270, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
